# Scraping

In [1]:
import yfinance as yf
import pandas
import numpy

In [3]:
tickers = ['NIFTYBEES.NS', 'MID150BEES.NS', 'MON100.NS', 'GOLDBEES.NS', 'LIQUIDBEES.NS']
print("Downloading data")
data = yf.download(tickers, period = '5y')['Close']
data.head()

Downloading data

[*********************100%***********************]  5 of 5 completed

Ticker,GOLDBEES.NS,LIQUIDBEES.NS,MID150BEES.NS,MON100.NS,NIFTYBEES.NS
Date,,,,,
2021-04-27,41.080002,831.941956,91.620003,103.233002,156.830002
2021-04-28,40.639999,831.941956,93.010002,102.971001,158.899994
2021-04-29,40.720001,831.950562,93.019997,102.670998,159.100006
2021-04-30,40.590000,833.575623,92.089996,102.077003,157.000000
2021-05-03,40.689999,833.575623,92.400002,101.959999,156.970001

In [4]:
returns = data.pct_change().dropna()
returns.head()

C:\Users\athre\AppData\Local\Temp\ipykernel_33724\582017148.py:1: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  returns = data.pct_change().dropna()

Ticker      GOLDBEES.NS  LIQUIDBEES.NS  MID150BEES.NS  MON100.NS  NIFTYBEES.NS
Date
2021-04-28    -0.010711       0.000000       0.015171  -0.002538      0.013199
2021-04-29     0.001969       0.000010       0.000107  -0.002913      0.001259
2021-04-30    -0.003193       0.001953      -0.009998  -0.005785     -0.013199
2021-05-03     0.002464       0.000000       0.003366  -0.001146     -0.000191
2021-05-04     0.001475       0.000000      -0.000649  -0.007885     -0.009046

In [5]:
mean_returns = returns.mean() * 252
print("Annualised Mean Returns\n")
print(mean_returns)

Annualised Mean Returns

Ticker
GOLDBEES.NS      0.241450
LIQUIDBEES.NS    0.037585
MID150BEES.NS    0.200396
MON100.NS        1.876497
NIFTYBEES.NS     0.120695
dtype: float64

In [6]:
cov_matrix = returns.cov() * 252
print("Annualised Covariance Matrix\n")
print(cov_matrix)

Annualised Covariance Matrix

Ticker         GOLDBEES.NS  LIQUIDBEES.NS  MID150BEES.NS  MON100.NS  \
Ticker
GOLDBEES.NS       0.031108       0.000038       0.001995   0.004470
LIQUIDBEES.NS     0.000038       0.000135       0.000159  -0.000302
MID150BEES.NS     0.001995       0.000159       0.026120   0.028713
MON100.NS         0.004470      -0.000302       0.028713  16.440152
NIFTYBEES.NS      0.001512       0.000041       0.015050   0.016679

Ticker         NIFTYBEES.NS
Ticker
GOLDBEES.NS        0.001512
LIQUIDBEES.NS      0.000041
MID150BEES.NS      0.015050
MON100.NS          0.016679
NIFTYBEES.NS       0.015808

In [8]:
data.to_csv("historical_prices.csv")
mean_returns.to_frame(name='Mean Returns').to_csv('mean_returns.csv')
cov_matrix.to_csv('cov_matrix.csv')
print("Data successfully saved to CSV files!")

Data successfully saved to CSV files!