# Scraping

In [38]:
import yfinance as yf
import pandas as pd
import numpy as np

In [39]:
tickers = ['TCS.NS', 'HDFCBANK.NS', 'RELIANCE.NS', 'SUNPHARMA.NS', 'ITC.NS']
print("Downloading data")
data = yf.download(tickers, start = "2014-01-01", end = "2023-12-31")['Close']
data.head()

[                       0%                       ]

Downloading data

[*********************100%***********************]  5 of 5 completed

Ticker      HDFCBANK.NS      ITC.NS  RELIANCE.NS  SUNPHARMA.NS      TCS.NS
Date
2014-01-01   150.498566  138.952728   188.334061    523.221313  811.153198
2014-01-02   148.654556  135.741791   185.409897    524.592712  816.314148
2014-01-03   150.034714  135.655609   183.131989    529.940491  837.108093
2014-01-06   149.717972  136.043488   181.161377    537.756775  843.662598
2014-01-07   150.328873  136.496048   178.438477    543.195862  831.061646

In [40]:
print(f"Number of missing values: {data.isna().sum().sum()}")

returns = data.pct_change().dropna()
returns.head()

Number of missing values: 0

Ticker      HDFCBANK.NS    ITC.NS  RELIANCE.NS  SUNPHARMA.NS    TCS.NS
Date
2014-01-02    -0.012253 -0.023108    -0.015526      0.002621  0.006362
2014-01-03     0.009284 -0.000635    -0.012286      0.010194  0.025473
2014-01-06    -0.002111  0.002859    -0.010761      0.014749  0.007830
2014-01-07     0.004080  0.003327    -0.015030      0.010114 -0.014936
2014-01-08     0.000452  0.000473     0.008253      0.011276  0.012012

In [41]:
print("Annualised Expected Returns:")
mean_returns = returns.mean() * 252
print(mean_returns)

Annualised Expected Returns:
Ticker
HDFCBANK.NS     0.200131
ITC.NS          0.142380
RELIANCE.NS     0.234910
SUNPHARMA.NS    0.131818
TCS.NS          0.179407
dtype: float64

In [42]:
print("Annualised Risk: ")
std_returns = returns.std() * np.sqrt(252)
print(std_returns)

Annualised Risk:
Ticker
HDFCBANK.NS     0.224637
ITC.NS          0.253520
RELIANCE.NS     0.278373
SUNPHARMA.NS    0.297809
TCS.NS          0.240271
dtype: float64

In [43]:
cov_matrix = returns.cov() * 252
print("Annualised Covariance Matrix\n")
print(cov_matrix)

Annualised Covariance Matrix

Ticker        HDFCBANK.NS    ITC.NS  RELIANCE.NS  SUNPHARMA.NS    TCS.NS
Ticker
HDFCBANK.NS      0.050462  0.016109     0.025399      0.012993  0.012419
ITC.NS           0.016109  0.064272     0.016224      0.013738  0.010716
RELIANCE.NS      0.025399  0.016224     0.077492      0.018568  0.016215
SUNPHARMA.NS     0.012993  0.013738     0.018568      0.088690  0.012462
TCS.NS           0.012419  0.010716     0.016215      0.012462  0.057730

In [44]:
# Save data to CSV 
returns.to_csv('stock_data.csv')
mean_returns.to_csv('mean_returns.csv')
std_returns.to_csv('std_returns.csv')
cov_matrix.to_csv('cov_matrix.csv')